{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimDate\",\"DimCity\",\"DimSalesperson\",\"DimCustomer\",\"DimProduct\",\"FactSales\",\"DimTarget\",\"ColorFormats\",\"Employee_csv\",\"DimCategory\",\"Fact Order\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pl-PL",
    "cultures": [
      {
        "name": "pl-PL",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "ColorFormats",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Źródło = Csv.Document(File.Contents(\"C:\\Users\\Krzys\\Desktop\\power bi2\\Dodatkowe dane\\Color Formats.csv\"),[Delimiter=\";\", Columns=3, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
          "    #\"Zmieniono typ\" = Table.TransformColumnTypes(Źródło,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
          "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(#\"Zmieniono typ\", [PromoteAllScalars=true]),",
          "    #\"Zmieniono typ1\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"Color\", type text}, {\"Background Color Format\", type text}, {\"Font Color Format\", type text}})",
          "in",
          "    #\"Zmieniono typ1\""
        ],
        "kind": "m",
        "lineageTag": "53128f51-401d-4e7d-98d5-4be71f5cc233"
      }
    ],
    "relationships": [
      {
        "name": "146b6bb6-c512-4612-bb5d-f7b236a357af",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Delivery Date",
        "fromTable": "FactSales",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "c2e1ed1b-b506-4bda-b00b-615c386d26d5",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Invoice Date",
        "fromTable": "FactSales",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "c671a3c7-88a5-4bf3-a6d6-fe02cbefc39e",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "City Key",
        "fromTable": "FactSales",
        "toColumn": "City Key",
        "toTable": "DimCity"
      },
      {
        "name": "ebd52bb3-889f-44b8-88c8-349ff5860784",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Salesperson Key",
        "fromTable": "FactSales",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      },
      {
        "name": "1ffce8bf-af7a-40a0-b553-d4538428a6ec",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Customer Key",
        "fromTable": "FactSales",
        "toColumn": "Customer Key",
        "toTable": "DimCustomer"
      },
      {
        "name": "bc9910b1-0204-e002-ec25-af54b4b85ccf",
        "fromColumn": "Stock Item Key",
        "fromTable": "FactSales",
        "toColumn": "Stock Item Key",
        "toTable": "DimProduct"
      },
      {
        "name": "b993717f-d9e9-0f71-ac88-4b03170a843d",
        "fromColumn": "EmployeeID",
        "fromTable": "DimTarget",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      },
      {
        "name": "e9825538-2267-7f93-41b9-4fb6d58e8df9",
        "fromColumn": "TargetMonth",
        "fromTable": "DimTarget",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "7bc16290-ec30-4cb2-b701-d2126abfc6f5",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "City Key",
        "fromTable": "Fact Order",
        "toColumn": "City Key",
        "toTable": "DimCity"
      },
      {
        "name": "a7a20d71-8ef5-402b-b94e-029eb7471d17",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Customer Key",
        "fromTable": "Fact Order",
        "toColumn": "Customer Key",
        "toTable": "DimCustomer"
      },
      {
        "name": "a715a0e5-fefb-4ccd-ab62-bc7bc3098269",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Order Date Key",
        "fromTable": "Fact Order",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "21b4c4f1-b7fe-45cb-aaf4-b2e587e3e349",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Picked Date Key",
        "fromTable": "Fact Order",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "b991fe4f-d9d1-41e5-86cd-05e81c8ae4ae",
        "fromColumn": "WWI Employee ID",
        "fromTable": "DimSalesperson",
        "toColumn": "WWI Employee ID",
        "toTable": "Employee_csv"
      },
      {
        "name": "a1fd2077-e8f7-440d-3640-193b97c548e3",
        "fromColumn": "Stock Item Key",
        "fromTable": "Fact Order",
        "toColumn": "Stock Item Key",
        "toTable": "DimProduct"
      },
      {
        "name": "81067c30-052f-4048-825e-638e368611f0",
        "fromColumn": "WWI Stock Item ID",
        "fromTable": "DimProduct",
        "toColumn": "WWI Stock Item ID",
        "toTable": "DimCategory"
      },
      {
        "name": "f5cb67ff-59ed-c6fc-4623-a618153857ed",
        "fromColumn": "Description",
        "fromTable": "Fact Order",
        "isActive": false,
        "toColumn": "Description",
        "toTable": "DimCategory"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "8862222b-b1c6-45d2-bc26-1999619c6570",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b49cb77-4d66-4c5d-8027-5092ae223a14",
            "sourceColumn": "Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dfe800f-000d-48bb-940e-78ad1a706d63",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3b28152-504e-43d9-8cda-8a2cfbacc1c3",
            "sortByColumn": "Calendar Month Number",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Short Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d05fcb4b-ee77-4a8b-a7b5-acf517b9b491",
            "sourceColumn": "Short Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7bc90451-6363-4cf8-9512-5b44932e7ea6",
            "sourceColumn": "Calendar Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a9a1cf5-59e1-4a9e-8ac2-be6fe2af3f86",
            "sourceColumn": "Calendar Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e37377d2-64bd-4253-ab5a-390bb72903f9",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3a63925-29f2-45f6-9905-c8f8e18c397f",
            "sourceColumn": "Calendar Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8b3cf92-a8c2-4600-8e44-71f289c8f7d2",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2b86ee0-24e2-45e8-9e73-1f9f35d966a9",
            "sourceColumn": "Fiscal Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73f8fdbd-2bdc-4aa5-b10d-c412f9b2ab92",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f2ad02d-a464-4636-b132-0634b496f539",
            "sourceColumn": "Fiscal Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "ISO Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13535fb1-3ebd-45a7-a9d8-0052343b4e0d",
            "sourceColumn": "ISO Week Number",
            "summarizeBy": "sum"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchia",
            "levels": [
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5918a1d7-f7cb-42eb-bfad-d455f412a500",
                "ordinal": 1
              },
              {
                "name": "Calendar Year",
                "column": "Calendar Year",
                "lineageTag": "703de12c-92ff-4745-b87c-642d0dbf68db",
                "ordinal": 0
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "ba17b64d-573b-46bf-91f3-5260ce1975f0",
                "ordinal": 2
              }
            ],
            "lineageTag": "16f92bc8-c964-4c86-9ec8-6dc1474aee79"
          }
        ],
        "lineageTag": "c6967523-a270-4077-a4ed-9dddc1489ee4",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_Date = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Date\"]}[Data]",
                "in",
                "    Dimension_Date"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCity",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc61430b-943e-488a-9edd-2e148fae00da",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI City ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00487e27-5680-4182-b753-4f779f81d8b1",
            "sourceColumn": "WWI City ID",
            "summarizeBy": "count"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "3b0077a6-4ce7-4794-bd0b-252c87b54fdd",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "77aab2a3-ba9f-4396-85f4-59788ba7df50",
            "sourceColumn": "State Province",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "1065da35-46a1-4a90-b2dd-5830cff07dcc",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7417cd27-e2da-4848-a750-5a8e6c42450d",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ef14d8f-4d71-465f-a3d4-193234e57751",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d8312dc-6642-4a37-8699-328cac82c1da",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Subregion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c998cbbe-3bac-400d-b5af-03c9975a6a0e",
            "sourceColumn": "Subregion",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Recorded Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d07f27b3-5708-4e2d-ab2e-3c87e76e21c3",
            "sourceColumn": "Latest Recorded Population",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bcc333ba-b1b9-4161-8873-a0a5d85916a6",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "11d02cf5-bc53-4bde-8648-7e203c91a182",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0d7279b-713c-45e6-9119-07172f70b21f",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Regions",
            "levels": [
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "c7e2c011-af12-4b42-a321-45cae70d4ca6",
                "ordinal": 0
              },
              {
                "name": "State Province",
                "column": "State Province",
                "lineageTag": "d0378973-7a02-4158-a165-89e99cb21495",
                "ordinal": 1
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "8465b2dc-2fce-4b40-95ea-bd0fe7a40044",
                "ordinal": 2
              }
            ],
            "lineageTag": "0df618a4-2ba6-40f1-a764-97952641492d"
          }
        ],
        "lineageTag": "2b5b5f90-90c0-4ce7-9eb7-74034e6e1ad6",
        "partitions": [
          {
            "name": "DimCity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_City = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"City\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(Dimension_City,1),",
                "    #\"Usunięto kolumny\" = Table.RemoveColumns(#\"Usunięto pierwsze wiersze\",{\"Lineage Key\", \"Fact.Order\", \"Fact.Sale\"})",
                "in",
                "    #\"Usunięto kolumny\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimSalesperson",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EmployeeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42b2ba2d-62e0-4a7e-8bc2-9ccf9cd27928",
            "sourceColumn": "EmployeeId",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a601bea7-643b-4da3-989f-83b31b3db230",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "684b3f4b-0675-4f4d-96cf-844ca86dfbd6",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2d9c9a60-5ecf-4486-a0af-ad7c9b3bb12c",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0c8ffea-b7f0-4d13-aba5-42bdb097e3fc",
            "sourceColumn": "First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15e80900-0963-4c43-a86c-4749113859ea",
            "sourceColumn": "Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "SalesPerson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd0462e6-36a6-4516-acb7-613d888cd630",
            "sourceColumn": "SalesPerson",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d707ebe0-f176-4a2f-9fc3-ec310bc0022b",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2338a21c-c8af-4911-8f1e-e4c6cd8500f3",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1809e8e3-c6bb-4d51-bdef-f6fe41ee2161",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9ad2077a-40d6-4607-bcf6-cf0c12d68f5d",
        "partitions": [
          {
            "name": "DimSalesperson",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_Employee = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Employee\"]}[Data],",
                "    #\"Przefiltrowano wiersze\" = Table.SelectRows(Dimension_Employee, each ([Is Salesperson] = true)),",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(#\"Przefiltrowano wiersze\",{\"Employee Key\", \"WWI Employee ID\", \"Employee\", \"Valid From\", \"Valid To\"}),",
                "    #\"Podzielono kolumnę według ogranicznika\" = Table.SplitColumn(#\"Usunięto inne kolumny\", \"Employee\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Employee.1\", \"Employee.2\"}),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Podzielono kolumnę według ogranicznika\",{{\"Employee.1\", type text}, {\"Employee.2\", type text}}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Zmieniono typ\",{{\"Employee.1\", \"First Name\"}, {\"Employee.2\", \"Last Name\"}}),",
                "    #\"Wstawiono scaloną kolumnę\" = Table.AddColumn(#\"Zmieniono nazwy kolumn\", \"SalesPerson\", each Text.Combine({[Last Name], [First Name]}, \" \"), type text),",
                "    #\"Scalone zapytania\" = Table.NestedJoin(#\"Wstawiono scaloną kolumnę\", {\"WWI Employee ID\"}, Employee_csv, {\"WWI Employee ID\"}, \"Employee_csv\", JoinKind.LeftOuter),",
                "    #\"Rozwinięty element Employee_csv\" = Table.ExpandTableColumn(#\"Scalone zapytania\", \"Employee_csv\", {\"JobTitle\", \"BusinessUnit\", \"Age\"}, {\"JobTitle\", \"BusinessUnit\", \"Age\"}),",
                "    #\"Zmieniono nazwy kolumn1\" = Table.RenameColumns(#\"Rozwinięty element Employee_csv\",{{\"Employee Key\", \"EmployeeId\"}})",
                "in",
                "    #\"Zmieniono nazwy kolumn1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9d6bc6e-0489-40c3-ad61-5982bcb68264",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d23c697-fbac-42f6-b88d-ace418cb44a3",
            "sourceColumn": "WWI Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a00a22a2-6355-4bb5-b704-b0d207ededa1",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Bill To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5725b531-90c4-40fe-85b7-f9f3930cbc5b",
            "sourceColumn": "Bill To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a904af3d-5152-4c9e-9cf8-f38988daf13d",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f44ca10-9a95-440f-82a3-eae4aebbecfa",
            "sourceColumn": "Buying Group",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "955d1ecc-bb8b-439c-9bb6-9af52c2d485d",
            "sourceColumn": "Primary Contact",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "88f7ca1f-430b-4552-b205-5181b8659841",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "12fadd41-0c47-48c3-8839-601b42da60c0",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bf696626-6c2c-45cf-8836-77a225f38083",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Customers",
            "levels": [
              {
                "name": "Buying Group",
                "column": "Buying Group",
                "lineageTag": "007f1464-a4ab-4112-b770-90de6f909a92",
                "ordinal": 0
              },
              {
                "name": "Customer",
                "column": "Customer",
                "lineageTag": "dc53955d-682b-44e2-bc7d-cb73ebe7c875",
                "ordinal": 1
              }
            ],
            "lineageTag": "2c7a3963-727d-49c4-bae8-4032a97eee1b"
          }
        ],
        "lineageTag": "02cfd262-34d7-4d13-9409-d5b4ca413600",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_Customer = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Customer\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(Dimension_Customer,1),",
                "    #\"Usunięto kolumny\" = Table.RemoveColumns(#\"Usunięto pierwsze wiersze\",{\"Lineage Key\", \"Fact.Movement\", \"Fact.Order\", \"Fact.Sale(Customer Key)\", \"Fact.Sale(Customer Key) 2\", \"Fact.Transaction(Customer Key)\", \"Fact.Transaction(Customer Key) 2\"})",
                "in",
                "    #\"Usunięto kolumny\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b70f537f-1494-409e-8466-46b54ba35787",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96ee79dc-c09d-49b9-abd6-ab2370903213",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "lineageTag": "04fe5cfe-e23a-40e8-9a7f-201a46d51588",
            "sourceColumn": "Stock Item",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f9bf631-b1be-4080-a9da-2b97f0a1f679",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a4fde9d-97fd-4f9b-a9c7-32646a444c1d",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bd59a54-45d2-45f4-87d7-6cd10f1da485",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c207cab-0a1c-4f6f-ac24-6fcc252dff1c",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Background Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "d07b0c30-8db1-4ddd-823d-577d68e7bf00",
            "sourceColumn": "Background Color Format",
            "summarizeBy": "none"
          },
          {
            "name": "Font Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "9f310c7c-62c8-47db-9517-5cc29b989a1f",
            "sourceColumn": "Font Color Format",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Products",
            "levels": [
              {
                "name": "Category",
                "column": "Category",
                "lineageTag": "a8203b78-6219-42ae-8837-a5e161bc418f",
                "ordinal": 0
              },
              {
                "name": "Stock Item",
                "column": "Stock Item",
                "lineageTag": "194b05d8-254f-4442-b2cf-d6f2e7087093",
                "ordinal": 1
              }
            ],
            "lineageTag": "82bce3e4-f74b-4bae-8b18-9371198cf6da"
          }
        ],
        "lineageTag": "e207a175-f40c-4c07-a271-e744f0657ddb",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    #\"Dimension_Stock Item\" = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(#\"Dimension_Stock Item\",1),",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(#\"Usunięto pierwsze wiersze\",{\"Stock Item Key\", \"WWI Stock Item ID\", \"Stock Item\", \"Color\", \"Unit Price\", \"Recommended Retail Price\"}),",
                "    #\"Scalone zapytania\" = Table.NestedJoin(#\"Usunięto inne kolumny\", {\"WWI Stock Item ID\"}, DimCategory, {\"WWI Stock Item ID\"}, \"DimCategory\", JoinKind.LeftOuter),",
                "    #\"Rozwinięty element DimCategory\" = Table.ExpandTableColumn(#\"Scalone zapytania\", \"DimCategory\", {\"Category\"}, {\"Category\"}),",
                "    #\"Scalone zapytania1\" = Table.NestedJoin(#\"Rozwinięty element DimCategory\", {\"Color\"}, ColorFormats, {\"Color\"}, \"ColorFormats\", JoinKind.LeftOuter),",
                "    #\"Rozwinięty element ColorFormats\" = Table.ExpandTableColumn(#\"Scalone zapytania1\", \"ColorFormats\", {\"Background Color Format\", \"Font Color Format\"}, {\"Background Color Format\", \"Font Color Format\"})",
                "in",
                "    #\"Rozwinięty element ColorFormats\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactSales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sale Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7284939-8bdf-4c24-9e72-e0b574ffa15a",
            "sourceColumn": "Sale Key",
            "summarizeBy": "count"
          },
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "898c0fd6-b36f-4fdd-badc-f04bb20876ba",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d54b16d1-51d4-4e64-b27e-750abacd340d",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "06e5a8ce-a152-4c00-8586-cf09fa013042",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c97ef6c1-5567-4daf-b68d-c13d896a99f7",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b0d631a1-5171-4edb-9968-1e9cf2606ece",
            "sourceColumn": "Salesperson Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21d0a9fe-79e8-45e1-9a9d-4429c54c2c15",
            "sourceColumn": "WWI Invoice ID",
            "summarizeBy": "count"
          },
          {
            "name": "Quantity(ilosc)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "c352e145-0bd9-4c68-b361-319d9e425574",
            "sourceColumn": "Quantity(ilosc)",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price(cena jednostkowa)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "918e98fc-ca4d-4c85-b51b-f9d059aa0a39",
            "sourceColumn": "Unit Price(cena jednostkowa)",
            "summarizeBy": "average"
          },
          {
            "name": "Tax Rate(vat%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "379954c5-2a24-410f-abdf-08ab24da97b1",
            "sourceColumn": "Tax Rate(vat%)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Excluding Tax(netto)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cf9d00ad-463b-47bd-9cb2-c726535648b7",
            "sourceColumn": "Total Excluding Tax(netto)",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Amount(vatpln)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5f98dea-6623-4602-a5d5-52d6af0ce148",
            "sourceColumn": "Tax Amount(vatpln)",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06f336f2-218b-45cf-bcc4-bfe7786a8f37",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Including Tax(brutto)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": [
              "Standard Tax",
              ""
            ],
            "lineageTag": "fcb8bb69-a9af-43d4-9066-46dbd9ae8878",
            "sourceColumn": "Total Including Tax(brutto)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Dry Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4fccda3-86fd-4153-8b60-939c20aef1fa",
            "sourceColumn": "Total Dry Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Chiller Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a10901e1-5b26-4608-8bb4-8eb05a31f339",
            "sourceColumn": "Total Chiller Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit case",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aea3db7b-c3bf-4056-bad3-598e8b32bb04",
            "sourceColumn": "Profit case",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a3565e09-6499-4f2f-8fd2-ca733f5e4758",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Order level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH(TRUE(), [Total Excluding Tax(netto)] >1000, \"High\", [Total Excluding Tax(netto)] > 500, \"Medium\",\"Low\")",
            "isDataTypeInferred": true,
            "lineageTag": "a01e8405-9a8e-4552-92cc-d310e7e639b8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "03e2f02b-8408-48ca-976e-d11cf9e1d845",
        "measures": [
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('FactSales'[Total Excluding Tax(netto)]) - SUM('FactSales'[Profit])"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalSubtraction",
                  "version": 0
                }
              }
            ],
            "lineageTag": "c424d8fe-e9d4-4b2f-9d75-3fd5fa1dfa7b"
          },
          {
            "name": "Profit margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE(SUM('FactSales'[Profit]), SUM('FactSales'[Total Excluding Tax(netto)]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalDivision",
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0da4e692-338d-4188-a686-415ed8bdec3b"
          }
        ],
        "partitions": [
          {
            "name": "FactSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Fact_Sale = WideWorldImportersDW{[Schema=\"Fact\",Item=\"Sale\"]}[Data],",
                "    #\"Usunięto inne kolumny\" = Table.SelectColumns(Fact_Sale,{\"Sale Key\", \"City Key\", \"Customer Key\", \"Stock Item Key\", \"Invoice Date Key\", \"Delivery Date Key\", \"Salesperson Key\", \"WWI Invoice ID\", \"Quantity\", \"Unit Price\", \"Tax Rate\", \"Total Excluding Tax\", \"Tax Amount\", \"Profit\", \"Total Including Tax\", \"Total Dry Items\", \"Total Chiller Items\"}),",
                "    #\"Zmieniono nazwy kolumn\" = Table.RenameColumns(#\"Usunięto inne kolumny\",{{\"Invoice Date Key\", \"Invoice Date\"}, {\"Delivery Date Key\", \"Delivery Date\"}}),",
                "    #\"Dodano kolumnę warunkową\" = Table.AddColumn(#\"Zmieniono nazwy kolumn\", \"Profit case\", each if [Profit] > 0 then \"Positive\" else \"Negative\"),",
                "    #\"Zmieniono nazwy kolumn1\" = Table.RenameColumns(#\"Dodano kolumnę warunkową\",{{\"Unit Price\", \"Unit Price(cena jednostkowa)\"}, {\"Tax Rate\", \"Tax Rate(vat%)\"}, {\"Tax Amount\", \"Tax Amount(vatpln)\"}, {\"Quantity\", \"Quantity(ilosc)\"}, {\"Total Including Tax\", \"Total Including Tax(brutto)\"}, {\"Total Excluding Tax\", \"Total Excluding Tax(netto)\"}})",
                "in",
                "    #\"Zmieniono nazwy kolumn1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimTarget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5461b4c2-b855-40b8-9cff-8e839230a669",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ee52092-fad1-4a2c-b885-a97320ec2aef",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "Atrybut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc149e3-7822-487f-8c55-474958b4e4bc",
            "sourceColumn": "Atrybut",
            "summarizeBy": "none"
          },
          {
            "name": "Wartość",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63e444fe-248b-47b8-9d67-bd070247db76",
            "sourceColumn": "Wartość",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e82deecb-df0a-4ce5-9ac3-e1695e71e74a",
            "sourceColumn": "TargetMonth",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d1e74d83-9eff-4b6a-91b6-0d9d560b686f",
        "partitions": [
          {
            "name": "DimTarget",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Csv.Document(File.Contents(\"C:\\Users\\Krzys\\Desktop\\power bi2\\Dodatkowe dane\\SalespersonTargets.csv\"),[Delimiter=\";\", Columns=14, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
                "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(Źródło, [PromoteAllScalars=true]),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"Year\", Int64.Type}, {\"EmployeeID\", Int64.Type}, {\"M01\", Int64.Type}, {\"M02\", Int64.Type}, {\"M03\", Int64.Type}, {\"M04\", Int64.Type}, {\"M05\", Int64.Type}, {\"M06\", Int64.Type}, {\"M07\", Int64.Type}, {\"M08\", Int64.Type}, {\"M09\", Int64.Type}, {\"M10\", Int64.Type}, {\"M11\", Int64.Type}, {\"M12\", Int64.Type}}),",
                "    #\"Anulowano przestawienie innych kolumn1\" = Table.UnpivotOtherColumns(#\"Zmieniono typ\", {\"Year\", \"EmployeeID\"}, \"Atrybut\", \"Wartość\"),",
                "    #\"Wyodrębniony tekst za ogranicznikiem\" = Table.TransformColumns(#\"Anulowano przestawienie innych kolumn1\", {{\"Atrybut\", each Text.AfterDelimiter(_, \"M\"), type text}}),",
                "    #\"Wstawiono scaloną kolumnę\" = Table.AddColumn(#\"Wyodrębniony tekst za ogranicznikiem\", \"TargetMonth\", each Text.Combine({\"01-\",[Atrybut], \"-\", Text.From([Year], \"pl-PL\")}), type text),",
                "    #\"Kolumna używana podczas mnożenia\" = Table.TransformColumns(#\"Wstawiono scaloną kolumnę\", {{\"Wartość\", each _ * 1000, type number}}),",
                "    #\"Zmieniono typ1\" = Table.TransformColumnTypes(#\"Kolumna używana podczas mnożenia\",{{\"TargetMonth\", type date}})",
                "in",
                "    #\"Zmieniono typ1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee_csv",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7fc71fd3-5963-47d4-b768-00e63e1e9c51",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e4de293-c3a3-45cf-8f31-60baf650769e",
            "sourceColumn": "Employee",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8f9a5f4-7f12-4bc2-861b-83d604c6f6cf",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64cc4eed-a774-4bd4-9e87-b5073824b28d",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9362978-3a39-4699-95d8-aee2a72d3a46",
            "sourceColumn": "Age",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6357d616-1fd9-490f-967e-c79b3f5f7408",
        "partitions": [
          {
            "name": "Employee_csv",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Csv.Document(File.Contents(\"C:\\Users\\Krzys\\Desktop\\power bi2\\Dodatkowe dane\\Employee_csv.csv\"),[Delimiter=\";\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(Źródło, [PromoteAllScalars=true]),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"WWI Employee ID\", Int64.Type}, {\"Employee\", type text}, {\"JobTitle\", type text}, {\"BusinessUnit\", type text}, {\"Age\", Int64.Type}})",
                "in",
                "    #\"Zmieniono typ\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3310e005-4246-442c-8cbd-2ea2229fd603",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "409f3c72-91a5-41ea-a4f4-a57d13c22881",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d1318c03-08e6-4f18-82b2-6facd47abc3e",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "32f23324-c4bb-40b9-8526-a803a2bd700b",
        "partitions": [
          {
            "name": "DimCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Excel.Workbook(File.Contents(\"C:\\Users\\Krzys\\Desktop\\power bi2\\Dodatkowe dane\\Category_dictionary.xlsx\"), null, true),",
                "    Arkusz1_Sheet = Źródło{[Item=\"Arkusz1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(Arkusz1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"WWI Stock Item ID\", Int64.Type}, {\"Description\", type text}, {\"Category\", type text}})",
                "in",
                "    #\"Zmieniono typ\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "db9fc6ef500b473b974e13441bed4594"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "84232956-e492-45f1-b4e3-b6129bfd0624",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e6db946a-2093-4d78-8e2b-a7edaa750758",
        "measures": [
          {
            "name": "Average Price",
            "displayFolder": "Pricing",
            "expression": "AVERAGE(FactSales[Unit Price(cena jednostkowa)])",
            "formatString": "0.00",
            "lineageTag": "cb5d6e94-d81e-4398-8885-884ef2f6cd9a"
          },
          {
            "name": "Total Profit",
            "expression": "SUM(FactSales[Profit])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ef49aa81-8272-4f8d-a65a-e1ca84e6ab37"
          },
          {
            "name": "Total Net Sales",
            "expression": "SUM(FactSales[Total Excluding Tax(netto)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8ee19dfe-ff4f-4e39-87a1-3a8f906056ce"
          },
          {
            "name": "Profit_Margin",
            "expression": "DIVIDE([Total Profit], [Total Net Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "554914cc-31e8-46c2-99dc-29b0449549eb"
          },
          {
            "name": "MIN Price",
            "displayFolder": "Pricing",
            "expression": "MIN(FactSales[Unit Price(cena jednostkowa)])",
            "formatString": "0.00",
            "lineageTag": "b0f39d22-91b9-418f-a8ee-81da56728f42"
          },
          {
            "name": "MAX Price",
            "displayFolder": "Pricing",
            "expression": "MAX(FactSales[Unit Price(cena jednostkowa)])",
            "formatString": "0.00",
            "lineageTag": "b80e5239-6cf4-4982-a6e2-cb01b6f5be16"
          },
          {
            "name": "MEDIAN Price",
            "displayFolder": "Pricing",
            "expression": "MEDIAN(FactSales[Unit Price(cena jednostkowa)])",
            "formatString": "0.00",
            "lineageTag": "2ea79983-491f-4290-aef6-473594504200"
          },
          {
            "name": "Sales 2014",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales], 'DimDate'[Calendar Year]=2014)",
            "lineageTag": "77f2f20a-1dc7-47d4-b9c9-36d763ccf60a"
          },
          {
            "name": "Filter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales],FILTER(FactSales, FactSales[Total Excluding Tax(netto)]>5000))",
            "lineageTag": "ef6d32bc-5726-4058-9e0c-d7eeccfa952a"
          },
          {
            "name": "Seles PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales],FILTER(DimProduct,DimProduct[Category] = \"Packaging Materials\")) ",
            "lineageTag": "93b094a0-9d54-4820-9f04-55f23ebbd381"
          },
          {
            "name": "YTD Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": "TOTALYTD([Total Net Sales], 'DimDate'[Date])",
            "lineageTag": "a015ead2-f3fa-4508-8c44-a8d924af9035"
          },
          {
            "name": "YTD-1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": "CALCULATE([YTD Total Sales],SAMEPERIODLASTYEAR('DimDate'[Date]))",
            "lineageTag": "9a31470f-99ed-4950-93e7-016be07886dd"
          },
          {
            "name": "YTD vs YTD -1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": "[YTD Total Sales] - [YTD-1 Total Sales]",
            "lineageTag": "db00fea5-4099-456a-8693-afd604ae3230"
          },
          {
            "name": "YTD vs YTD -1 Total Sales Procent",
            "displayFolder": "YTD",
            "expression": "([YTD Total Sales] - [YTD-1 Total Sales])/[YTD-1 Total Sales]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4c82edd5-c055-433c-8113-57847ba15171"
          },
          {
            "name": "Total Sales YearAgo Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([Total Net Sales], PARALLELPERIOD('DimDate'[Date],",
              "-12, MONTH ))",
              ""
            ],
            "lineageTag": "1d4de5da-34e1-4068-906f-3e8befff8a0c"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM(FactSales[Quantity(ilosc)])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a53b633d-e943-404e-b3e7-ff334ae32087"
          },
          {
            "name": "Total Quantily cos",
            "expression": "CALCULATE([Total Quantity],PARALLELPERIOD('DimDate'[Date],-12,MONTH))",
            "formatString": "0",
            "lineageTag": "d5ebdcee-1135-4bff-a089-1c9c393d51ba"
          },
          {
            "name": "YTD vs YTD -1 Total Sales Quantitly Procent",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([YTD Total Sales] - [YTD-1 Total Sales])/[YTD-1 Total Sales]",
            "lineageTag": "00ec9753-be5d-4913-891f-47d3d7817b7e"
          },
          {
            "name": "YTD Total Quantity",
            "expression": "TOTALYTD([Total Quantity], 'DimDate'[Date])",
            "formatString": "0",
            "lineageTag": "a3bdf748-d530-4219-9bfa-b25fae58a9ef"
          },
          {
            "name": "Total Net Sales terretorium",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSales[Total Excluding Tax(netto)]),REMOVEFILTERS(DimCity[City]))",
            "lineageTag": "e9a3a8fd-ee83-42fc-8fba-4c1c52b06174"
          },
          {
            "name": "Sales Procent Teritory",
            "expression": "[Total Net Sales]/[Total Net Sales terretorium]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd061de7-fe35-44d5-a312-cbac1c820c4d"
          },
          {
            "name": "Total Net Sales Country",
            "expression": "CALCULATE(SUM(FactSales[Total Excluding Tax(netto)]),REMOVEFILTERS(DimCity[Sales Territory], DimCity[City]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "80af8cdd-728a-4900-900c-2cd822183b98"
          },
          {
            "name": "Sales % country",
            "expression": "[Total Net Sales]/[Total Net Sales Country]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b2cba2fa-9d5e-4b5f-878d-beba63ca7ab3"
          },
          {
            "name": "Categorize",
            "expression": "SWITCH(TRUE(), [Total Net Sales] >10000, \"High\",[Total Net Sales] >5000, \"Medium\",\"Low\")",
            "lineageTag": "83b5a182-73a3-435c-abc3-1a0d6ede1917"
          },
          {
            "name": "Total Orders",
            "expression": "DISTINCTCOUNT(FactSales[WWI Invoice ID])",
            "formatString": "0",
            "lineageTag": "26b24472-a31e-45ff-9de2-a044711d6b23"
          },
          {
            "name": "Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('DimTarget'[Wartość])",
            "lineageTag": "9858f9e7-408d-4b08-9cd9-3f05ba99a75a"
          },
          {
            "name": "Target YTD",
            "expression": "TOTALYTD([Target], 'DimDate'[Date])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "01b0de04-953c-42ff-863f-c09950200017"
          },
          {
            "name": "Sales - Target diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[YTD Total Sales] - [Target YTD]",
            "lineageTag": "44edcbce-5409-4424-a08d-3f4ea28a9239"
          },
          {
            "name": "Sales - Target diff %",
            "expression": "DIVIDE([Sales - Target diff], [YTD Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "221cd5f6-839f-4f4d-8b28-fea2d12b6c01"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity",
            "expression": "[YTD Total Quantity]-[YTD-1 Total Quantity]",
            "lineageTag": "39b01ec5-8523-4211-9f97-596e7cfcdce7"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity precentage",
            "expression": "[YTD vs YTD-1 Total Quantity]/[YTD-1 Total Quantity]",
            "lineageTag": "16dfc558-5325-4655-8353-b910851c6de1"
          },
          {
            "name": "YTD-1 Total Quantity",
            "expression": "CALCULATE([YTD Total Quantity], SAMEPERIODLASTYEAR('DimDate'[Date]))",
            "lineageTag": "0bf313f1-9971-4b5b-b2ec-31da8fbfe846"
          }
        ],
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dates_1",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "116bfb4139764dcb8458157a269d033e"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a140b37e-f7d9-466b-a902-264a5922f8f7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Dates_1'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34e40949-3375-4460-b6ec-0a2b8f4e8f9f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Dates_1'[Date],\"mmm\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2683392e-6b04-4c66-b3ed-7509f9439d73",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\"FY\" & YEAR('Dates_1'[Date]) + IF(MONTH('Dates_1'[Date]) > 6, 1)",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "81813460-ae37-4a64-9eab-1cfa478a6ab5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "(YEAR('Dates_1'[Date]) * 100) + MONTH('Dates_1'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d21a3374-eede-46c4-b80f-470c5f42e168",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "MONTH('Dates_1'[Date])",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4c7169e7-d4f9-418f-8d04-b9f949f9aa1e",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "90630ca3-720e-4c16-a5d9-fb56509aa199",
        "measures": [
          {
            "name": "Sales Contribution by Customer % (procentowy udzial klijenta)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Customer(sprzedaz dla klijenta)],",
              "    CALCULATE(SUM(FactSales[Total Including Tax(brutto)])),",
              "    0",
              ")",
              ""
            ],
            "lineageTag": "a50cac15-bf94-44f9-9ab8-356af11a1168"
          }
        ],
        "partitions": [
          {
            "name": "Dates_1",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(2022, 1, 1), DATE(2023, 03, 31))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_Date2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1daab559b28245c09b0b2fe0210dc143"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ea654344-0818-4eac-a4c7-f774eb5dfd80",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "74c0d875-2153-4a7d-8c00-726b5a7022f0",
            "sourceColumn": "[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6b46a969-ca40-47eb-babd-7b61b88e618a",
            "sourceColumn": "[Year Start]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearEnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "318d5c79-d6c4-4385-86ec-443c9e6d9684",
            "sourceColumn": "[YearEnd]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f8bb19cd-dea1-40f1-81df-21b65567ddf5",
            "sourceColumn": "[MonthNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6ed22426-0700-4465-8f22-2eb758edf390",
            "sourceColumn": "[MonthStart]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthEnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7893139c-bb12-4b6a-9b95-3a6db61b4536",
            "sourceColumn": "[MonthEnd]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DaysInMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "82817f15-82cc-4f80-baa3-3a27a2c72d59",
            "sourceColumn": "[DaysInMonth]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a30e80da-f988-40e1-9cb3-38bef2632485",
            "sourceColumn": "[YearMonthNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ce0e9572-afbc-4504-b504-8ba5b12f7b49",
            "sourceColumn": "[YearMonthName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5e1e16be-d33e-4b9c-8371-a8edf6a0e6c6",
            "sourceColumn": "[DayNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b4e3410f-e85d-40cd-b27b-69701566d14e",
            "sourceColumn": "[DayName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNameShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "62792808-30bf-43d0-8dfd-d0ac2a34501a",
            "sourceColumn": "[DayNameShort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3eb70169-a5eb-49a7-9145-6dbc31539293",
            "sourceColumn": "[DayOfWeek]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0d5faaad-80b7-4af1-a264-e3def2a22e89",
            "sourceColumn": "[MonthName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNameShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4ec14fe8-785c-406f-b8c8-41132f6cf1ca",
            "sourceColumn": "[MonthNameShort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f3fe83ba-f8a0-43dc-8c68-64614d7311b7",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b6cbadad-36fc-48c8-afe5-62a4d1e77eb5",
            "sourceColumn": "[QuarterName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearQuarterNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d57b3c05-dcd7-4d29-bbcf-41afa7820c2e",
            "sourceColumn": "[YearQuarterNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearQuarterName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b4d07ace-0434-4458-814d-51e8fd86bc8d",
            "sourceColumn": "[YearQuarterName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72576665-ac1b-48bd-8123-3f66d614026a",
            "sourceColumn": "[QuarterStart]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterEnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b5f174c9-a93a-4e6e-b211-3ea7b803539f",
            "sourceColumn": "[QuarterEnd]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dd168a0b-f9eb-441d-8c37-acf320d2e3c1",
            "sourceColumn": "[WeekNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bfbf4e75-4269-4fff-8fb4-a4b10efcac41",
            "sourceColumn": "[WeekStart]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekEnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "79adb60d-f85f-434d-b109-ae20692b3f3d",
            "sourceColumn": "[WeekEnd]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4a836533-75e4-4442-b016-adb2031b2e81",
            "sourceColumn": "[FiscalYear]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4ca1081e-5af3-49d8-97c3-b2c76b1d131f",
            "sourceColumn": "[FiscalQuarter]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6d7f931b-85ac-49c9-8810-fd1c3cfdaeb3",
            "sourceColumn": "[FiscalMonth]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "dcb5c932-c07c-4cda-8c2d-f6e7182471a7",
        "partitions": [
          {
            "name": "Dim_Date2",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _minYear = YEAR(MIN(FactSales[Invoice Date]))",
                "VAR _maxYear = YEAR(MAX(FactSales[Invoice Date]))",
                "VAR _fiscalStart = 4 ",
                "",
                "RETURN",
                "ADDCOLUMNS(",
                "",
                "    CALENDAR(",
                "",
                "                DATE(_minYear,1,1),",
                "",
                "                DATE(_maxYear,12,31)",
                "",
                "),",
                "",
                "\"Year\",YEAR([Date]),",
                "\"Year Start\",DATE( YEAR([Date]),1,1),",
                "\"YearEnd\",DATE( YEAR([Date]),12,31),",
                "\"MonthNumber\",MONTH([Date]),",
                "\"MonthStart\",DATE( YEAR([Date]), MONTH([Date]), 1),",
                "\"MonthEnd\",EOMONTH([Date],0),",
                "\"DaysInMonth\",DATEDIFF(DATE( YEAR([Date]), MONTH([Date]), 1),EOMONTH([Date],0),DAY)+1,",
                "\"YearMonthNumber\",INT(FORMAT([Date],\"YYYYMM\")),",
                "\"YearMonthName\",FORMAT([Date],\"YYYY-MMM\"),",
                "\"DayNumber\",DAY([Date]),",
                "\"DayName\",FORMAT([Date],\"DDDD\"),",
                "\"DayNameShort\",FORMAT([Date],\"DDD\"),",
                "\"DayOfWeek\",WEEKDAY([Date]),",
                "\"MonthName\",FORMAT([Date],\"MMMM\"),",
                "\"MonthNameShort\",FORMAT([Date],\"MMM\"),",
                "\"Quarter\",QUARTER([Date]),",
                "\"QuarterName\",\"Q\"&FORMAT([Date],\"Q\"),",
                "\"YearQuarterNumber\",INT(FORMAT([Date],\"YYYYQ\")),",
                "\"YearQuarterName\",FORMAT([Date],\"YYYY\")&\" Q\"&FORMAT([Date],\"Q\"),",
                "\"QuarterStart\",DATE( YEAR([Date]), (QUARTER([Date])*3)-2, 1),",
                "\"QuarterEnd\",EOMONTH(DATE( YEAR([Date]), QUARTER([Date])*3, 1),0),",
                "\"WeekNumber\",WEEKNUM([Date]),",
                "\"WeekStart\", [Date]-WEEKDAY([Date])+1,",
                "\"WeekEnd\",[Date]+7-WEEKDAY([Date]),",
                "\"FiscalYear\",if(_fiscalStart=1,YEAR([Date]),YEAR([Date])+ QUOTIENT(MONTH([Date])+ (13-_fiscalStart),13)),",
                "\"FiscalQuarter\",QUARTER( DATE( YEAR([Date]),MOD( MONTH([Date])+ (13-_fiscalStart) -1 ,12) +1,1) ),",
                "\"FiscalMonth\",MOD( MONTH([Date])+ (13-_fiscalStart) -1 ,12) +1",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Fact Order",
        "columns": [
          {
            "name": "Order Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12761edf-039f-4b6e-b236-f21bf43602c8",
            "sourceColumn": "Order Key",
            "summarizeBy": "count"
          },
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f2a6816-2c48-4159-a329-51d63dc12f14",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76173b19-f103-4c26-93ad-4c197fff0dc3",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75df31af-629f-4616-a95f-56f00b753b41",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2cb8fda1-2ad8-4dc7-a934-8f525c7f3364",
            "sourceColumn": "Order Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Picked Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0e29fb88-0aa7-4236-b18c-e6b0de166cf3",
            "sourceColumn": "Picked Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9671bd51-9dc2-4860-a48b-bd20d573c589",
            "sourceColumn": "Salesperson Key",
            "summarizeBy": "count"
          },
          {
            "name": "Picker Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee124146-1856-4772-bbe4-7563022d91a8",
            "sourceColumn": "Picker Key",
            "summarizeBy": "count"
          },
          {
            "name": "WWI Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6d3700e-3e44-418c-bd31-01cf705fcb69",
            "sourceColumn": "WWI Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "WWI Backorder ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2c95ff70-226b-4b12-9ca3-2aacefa62ae3",
            "sourceColumn": "WWI Backorder ID",
            "summarizeBy": "count"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf69f4ec-6f51-447e-8ea7-8c10be1cb97b",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6edc453d-b747-4c19-974b-2fedd6c63f7e",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "323ddd21-0f51-4435-bc29-a2b7c60b9fe8",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a96a5a4-daad-4baa-a488-4719cf4541e0",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8b012d4f-da54-4d31-aeec-2eed39081e8b",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Excluding Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d976f7c4-69c6-44d8-a247-ff34a3f63841",
            "sourceColumn": "Total Excluding Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2382c78a-8480-467e-9973-cddf8d0f5f86",
            "sourceColumn": "Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Including Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "260815c4-c459-45e2-bc7a-c9b23bbee375",
            "sourceColumn": "Total Including Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "20713e11-3200-4856-9d99-92f3132076f3",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "54d12b6d-a631-4684-b1d0-657a1086d82c",
        "partitions": [
          {
            "name": "Fact Order",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-IUEMVDK\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Fact_Order = WideWorldImportersDW{[Schema=\"Fact\",Item=\"Order\"]}[Data]",
                "in",
                "    Fact_Order"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure_raport_sprzedazy",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ba9f365a908542458b26ffd3f564d068"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ecd3b08-4842-45c7-ac7c-2ffe9c524888",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "eb4655d0-b24d-4bc3-af03-877a1ea4b2ad",
        "measures": [
          {
            "name": "Total Net Revenue",
            "description": [
              "Łączne przychody netto",
              ""
            ],
            "expression": [
              "SUM(FactSales[Sale Key])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e207fa8d-1259-462a-863c-d0a3f1533adb"
          },
          {
            "name": "Total Gross Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Łączne przychody brutto",
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)])",
              ""
            ],
            "lineageTag": "49533bb1-1328-4345-9026-7c83a25cc285"
          },
          {
            "name": "Total Tax Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Kwota podatku",
            "expression": [
              "SUM(FactSales[Tax Amount(vatpln)])",
              ""
            ],
            "lineageTag": "2f642820-154b-4665-9237-6b41fa6e56ba"
          },
          {
            "name": "Profit Margin_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Marża zysku",
            "expression": [
              "DIVIDE(SUM(FactSales[Profit]), SUM(FactSales[Sale Key]))",
              ""
            ],
            "lineageTag": "cdd50f9e-0d27-437e-a678-86e92949ff61"
          },
          {
            "name": "Top Products by Revenue",
            "description": "Najlepsze produkty według przychodów",
            "expression": [
              "",
              "TOPN(10, DimProduct, SUM(FactSales[Sale Key]), DESC)",
              ""
            ],
            "lineageTag": "abe58a18-1600-4bab-9eb1-38da60d485f6"
          },
          {
            "name": "Top Categories by Revenue",
            "description": "Najlepsze kategorie produktów według przychodów",
            "expression": [
              "",
              "TOPN(10, DimCategory[Category], SUM(FactSales[Sale Key]), DESC)",
              ""
            ],
            "lineageTag": "5888397b-4e16-4e90-9a0b-fd268199d5e7"
          },
          {
            "name": "Most Popular Product Name",
            "description": "Najpopularniejszy produkt według liczby sprzedanych sztuk",
            "expression": [
              "",
              "CALCULATE(",
              "    FIRSTNONBLANK(DimProduct[Product Name], 1),",
              "    TOPN(",
              "        1, ",
              "        DimProduct, ",
              "        SUM(FactSales[Quantity]), ",
              "        DESC",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "6f7cfa9e-9e64-4293-8cfb-028c45429f7b"
          }
        ],
        "partitions": [
          {
            "name": "Measure_raport_sprzedazy",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f10f432e7a3d4213b8fd5efa8508bc96"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8cad0ef8-fdcb-457a-98b3-c1220ee83399",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2f78f306-f111-462f-8b6b-eab440d70a28",
        "measures": [
          {
            "name": "Net Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM('FactSales'[Total Excluding Tax(netto)])",
              ""
            ],
            "lineageTag": "e1180e39-41d8-4c61-9fe4-7e95b04b10d5"
          },
          {
            "name": "Tax Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM('FactSales'[Total Including Tax(brutto)]) - SUM('FactSales'[Total Excluding Tax(netto)])",
              ""
            ],
            "lineageTag": "d21896c8-3ef1-4a3d-8cef-c56e0d7813c4"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM('FactSales'[Profit])",
              ""
            ],
            "lineageTag": "1729c5d2-d071-47a6-8e7b-dff1dc5179cc"
          },
          {
            "name": "Sales Current Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DATESMTD('DimDate'[Date])",
              "    )",
              ""
            ],
            "lineageTag": "98e92190-7c78-4475-bd09-64fac681d58e"
          },
          {
            "name": "Sales Current Quarter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DATESQTD('DimDate'[Date])",
              "    )",
              ""
            ],
            "lineageTag": "1ef547b0-d0c5-491d-9160-b37e2d96076f"
          },
          {
            "name": "Sales Current Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DATESYTD('DimDate'[Date])",
              "    )",
              ""
            ],
            "lineageTag": "314734aa-e2e0-40d6-816f-487a10e9d8d4"
          },
          {
            "name": "Product Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM('FactSales'[Total Including Tax(brutto)])",
              ""
            ],
            "lineageTag": "cce1e91a-4ea7-455a-8a0a-b5d715dcce65"
          },
          {
            "name": "Product Rank",
            "expression": [
              "",
              "    RANKX(",
              "        ALL('DimProduct'),",
              "        [Product Sales],",
              "        ,",
              "        DESC",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "26db199a-dc27-48a2-bd58-15525a32c8f9"
          },
          {
            "name": "Sales per Salesperson",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM('FactSales'[Total Including Tax(brutto)])",
              ""
            ],
            "lineageTag": "dac50df0-680c-484b-9338-855294b4bac1"
          },
          {
            "name": "Transactions per Salesperson",
            "expression": [
              "",
              "    COUNTROWS('FactSales')",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9f8da555-16f2-48eb-bb41-297051e9e9c7"
          },
          {
            "name": "Transactions per Salesperson unikalne",
            "expression": [
              "",
              "    COUNT('FactSales'[Salesperson Key])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5ea08eb9-28dc-407b-a158-4d16adf44eef"
          },
          {
            "name": "Average Transaction Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DISTINCTCOUNT('FactSales'[Invoice Date]),",
              "        0",
              "    )",
              ""
            ],
            "lineageTag": "e7d00cde-1e8e-4618-b347-9c7b94a59c58"
          },
          {
            "name": "Sales YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DATESYTD('DimDate'[Date])",
              "    )",
              ""
            ],
            "lineageTag": "06a53fd7-5019-43da-aba0-4aa86fe49bb7"
          },
          {
            "name": "Sales MAT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        DATESINPERIOD(",
              "            'DimDate'[Date],",
              "            MAX('DimDate'[Date]),",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "c10c7e0f-4276-46ed-aeb6-495f44dadef9"
          },
          {
            "name": "Sales YoY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Sales(łaczna wartość sprzedaży)],",
              "        SAMEPERIODLASTYEAR('DimDate'[Date])",
              "    )",
              ""
            ],
            "lineageTag": "7e2c3034-02f3-440a-bf1d-81b06f254cd7"
          },
          {
            "name": "Sales YoY Change",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    [Sales YTD] - [Sales YoY]",
              ""
            ],
            "lineageTag": "834f77b1-4734-4cb6-b97b-91c00c5c3b69"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "{\"\"}",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Miary fact sales",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "027a606555d54fe18b9d0aa65e605f52"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bb2f33d2-0633-43ea-a215-f63ce9093bab",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "01a1a4ea-96aa-4439-9d04-94100a5feaf6",
        "measures": [
          {
            "name": "Total Sales(łaczna wartość sprzedaży)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)]",
              ")"
            ],
            "lineageTag": "83caf42b-4ab8-41d9-b97d-fb770d839abf"
          },
          {
            "name": "Net Sales(netto sprzedaz",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM(FactSales[Total Excluding Tax(netto)]",
              ")"
            ],
            "lineageTag": "e9f3c173-e27f-4b51-a5c4-2c2fb7c4adbf"
          },
          {
            "name": "Tax Amount(wartosc podatku)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM(FactSales[Tax Amount(vatpln)]",
              ")"
            ],
            "lineageTag": "ad6a95fa-3224-4fb3-9c10-a8c1d06b6337"
          },
          {
            "name": "Gross Sales(WARTOSC BRUTTO)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)]",
              ")"
            ],
            "lineageTag": "c0091c67-5d3d-42ae-879f-b2c1a266b91a"
          },
          {
            "name": "Profit Margin(wartosc zysku)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "DIVIDE(SUM(FactSales[Profit]), SUM(FactSales[Total Excluding Tax(netto)]), 0)",
              ""
            ],
            "lineageTag": "c882e023-e140-4358-9905-de06c31e2d2c"
          },
          {
            "name": "Monthly Sales(sprzedaz miesieczna)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSales[Total Including Tax(brutto)]),DATESMTD(DimDate[Date]))",
            "lineageTag": "d929a4cf-6bd0-41a2-8ad4-259505e4ad26"
          },
          {
            "name": "3 Monthly Sales(sprzedaz kwartalna)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSales[Total Including Tax(brutto)]),DATESQTD(DimDate[Date]))",
            "lineageTag": "57262588-5ad7-4e8a-9bbe-76ec14beb940"
          },
          {
            "name": "Year Sales(sprzedaz roczna)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSales[Total Including Tax(brutto)]),DATESYTD(DimDate[Date]))",
            "lineageTag": "09456c49-9ec6-43b1-b784-bbe92851f382"
          },
          {
            "name": "Profit Margin %",
            "expression": [
              "FORMAT([Profit Margin(wartosc zysku)], \"0.00%\")",
              ""
            ],
            "lineageTag": "c7c3580f-67af-4ab6-99e0-0d7be5f3b2f5"
          },
          {
            "name": "Product Total Sales(produkt najwieksze przychody)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)])",
              ""
            ],
            "lineageTag": "751ba1e4-1b2e-4494-82e2-15b88adea1dc"
          },
          {
            "name": "Product Quantity Sold(Produkt sprzedawany najwieksza ilosc)",
            "expression": [
              "SUM(FactSales[Quantity(ilosc)])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "550d9844-649d-44dc-908e-6dc8897374b6"
          },
          {
            "name": "Category Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSales[Total Including Tax(brutto)]), ALLEXCEPT(DimProduct, DimProduct[Category])) //allexcept usuwa filtry ",
            "lineageTag": "fa5d312f-d51e-477b-9d4d-2fd0ef510df6"
          },
          {
            "name": "Total Sales by Salesperson(łaczna sprzedaz dla sprzedawcy)",
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)])",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "67ceb46a-f0c3-4db2-8f15-3f9d33ad6f7c"
          },
          {
            "name": "Total Transactions by Salesperson(liczba tranzakcji przypisana do sprzedawcy)",
            "expression": [
              "COUNT(FactSales[Sale Key])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "82bbd839-eaad-4d41-83bb-31636786055c"
          },
          {
            "name": "Average Transaction Value(średnia wartosc tranzakcji)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Salesperson(łaczna sprzedaz dla sprzedawcy)], ",
              "    [Total Transactions by Salesperson(liczba tranzakcji przypisana do sprzedawcy)],",
              "    0",
              ")",
              ""
            ],
            "lineageTag": "f414b850-370f-40f9-9bb6-d4a06f850e47"
          },
          {
            "name": "Sales Contribution %(udział sprzedawcy %)",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Salesperson(łaczna sprzedaz dla sprzedawcy)], ",
              "    CALCULATE(SUM(FactSales[Total Including Tax(brutto)]), ALL(DimSalesperson[SalesPerson])),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d436020a-f5c3-4abb-b568-6dfd7d124cdc"
          },
          {
            "name": "Salesperson Rank (ranking)",
            "expression": [
              "",
              "RANKX(",
              "    ALL(DimSalesperson[SalesPerson]),",
              "    [Total Sales by Salesperson(łaczna sprzedaz dla sprzedawcy)],",
              "    ,",
              "    DESC",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "85c5e931-99e6-4f7c-8e58-0c3553df4c1a"
          },
          {
            "name": "Total Sales by Location(sprzedaz wedlug lokalizacji)",
            "expression": [
              "SUM(FactSales[Total Including Tax(brutto)])",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "eebdfe37-2a47-4b98-b71c-9f02308cec6f"
          },
          {
            "name": "Sales Contribution by Location % (procentowy udział wedlug lokalizacji)",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Location(sprzedaz wedlug lokalizacji)],",
              "      CALCULATE(SUM(FactSales[Total Including Tax(brutto)]), ALL(DimCity)),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "75541924-9d33-4888-bcc1-fd0786451478"
          },
          {
            "name": "Total Sales by Customer(sprzedaz dla klijenta)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    SUM(FactSales[Total Including Tax(brutto)])"
            ],
            "lineageTag": "fdd6aedb-e497-46d6-a1f0-4fdc0aae4da1"
          },
          {
            "name": "Customer Rank by Sales(ranking klijentów)",
            "expression": [
              "",
              "RANKX(",
              "    ALL(DimCustomer[Customer Key]), ",
              "    [Total Sales by Customer(sprzedaz dla klijenta)],",
              "    ,",
              "    DESC",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "dd7975d8-5086-4ef5-b2d0-b206b54b3828"
          },
          {
            "name": "Average Transaction Value by Customer (srednia wartosc tranzakcji",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Customer(sprzedaz dla klijenta)], ",
              "    [Total Transactions by Customer (liczba tranzakcji na klijenta],",
              "    0",
              ")",
              ""
            ],
            "lineageTag": "e4ffe605-6d6d-470c-af0b-81cec56926ef"
          },
          {
            "name": "Total Transactions by Customer (liczba tranzakcji na klijenta",
            "expression": [
              "COUNT(FactSales[Sale Key])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f9a980f0-1976-4c58-8eb7-599f83f9545f"
          },
          {
            "name": "Customer Sales Contribution %",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Sales by Customer(sprzedaz dla klijenta)],",
              "    CALCULATE(SUM(FactSales[Total Including Tax(brutto)]),",
              "    ALL(DimCustomer)),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0f5ca9b9-cef9-4569-a2c7-3a4767279971"
          },
          {
            "name": "Dynamic Sales_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(Okresy[Okres]) = \"Miesiąc\", [Monthly Sales(sprzedaz miesieczna)],",
              "    SELECTEDVALUE(Okresy[Okres]) = \"Kwartał\", [3 Monthly Sales(sprzedaz kwartalna)],",
              "    SELECTEDVALUE(Okresy[Okres]) = \"Rok\", [Year Sales(sprzedaz roczna)],",
              "    BLANK()",
              ")",
              ""
            ],
            "lineageTag": "bb63317d-6c15-4c62-9503-5f4053d8317d"
          }
        ],
        "partitions": [
          {
            "name": "Miary fact sales",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Okresy",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4d2cdd3e1c7a40d1be2803c792fca452"
          }
        ],
        "columns": [
          {
            "name": "Okres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8f7c06f4-2947-40e5-a15b-6d630752c842",
            "sourceColumn": "[Okres]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8ee952de-4bed-437e-a05c-aa7d6c633335",
        "partitions": [
          {
            "name": "Okresy",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(",
                "    \"Okres\", STRING,",
                "    {",
                "        {\"Miesiąc\"},",
                "        {\"Kwartał\"},",
                "        {\"Rok\"}",
                "    }",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}